str(input("Think  the 3-digit numbers, different from each other in your mind,  when you keep ,click enter."))
str(input("Subtract the number you are thinking from the opposite of the number you are thinking, subtract the smaller from the larger one, and press enter when you subtract it."))
a=int(input("What is the hundreds digit of the result? :"))
if a==0 :print("099")
elif a==1 :print("sonuç 198")
elif a==2 :print(" sonuç 297")
elif a==3:print("sonuç 396")
elif a==4:print(" sonuç 495")
elif a==5:print("sonuç 594")
elif a==6:print("sonuç 693")
elif a==7:print(" sonuç792")
elif a==8:print("sonuç 891")
elif a==9:print(" sonuç 990")
else :print("your maths is not perfect. quit the game and study")
str(input("Good Game"))

